SELECT
    HACKERS.HACKER_ID,
    HACKERS.NAME
FROM
    HACKERS,
    DIFFICULTY,
    CHALLENGES,
    SUBMISSIONS
WHERE
    HACKERS.HACKER_ID = SUBMISSIONS.HACKER_ID AND
    SUBMISSIONS.CHALLENGE_ID = CHALLENGES.CHALLENGE_ID AND
    DIFFICULTY.DIFFICULTY_LEVEL = CHALLENGES.DIFFICULTY_LEVEL AND
    SUBMISSIONS.SCORE = DIFFICULTY.SCORE
GROUP BY 
    HACKERS.HACKER_ID,
    HACKERS.NAME
HAVING COUNT(SUBMISSIONS.SUBMISSION_ID) > 1
ORDER BY
    COUNT(HACKERS.HACKER_ID) DESC,
    HACKERS.HACKER_ID ASC